package com.bc.wechat.server.enums;

/**
 * 返回消息
 *
 * @author zhou
 */
public enum ResponseMsg {
    /**
     * wechat-server接口返回信息
     */
    USER_EXISTS("USER_EXISTS", "用户已存在"),

    UPDATE_USER_NICK_NAME_SUCCESS("UPDATE_USER_NICK_NAME_SUCCESS", "修改昵称成功"),
    UPDATE_USER_NICK_NAME_ERROR("UPDATE_USER_NICK_NAME_ERROR", "修改昵称失败"),

    UPDATE_USER_WX_ID_SUCCESS("UPDATE_USER_WX_ID_SUCCESS", "修改微信号成功"),
    UPDATE_USER_WX_ID_ERROR("UPDATE_USER_WX_ID_ERROR", "修改微信号失败"),

    UPDATE_USER_SEX_SUCCESS("UPDATE_USER_SEX_SUCCESS", "修改性别成功"),
    UPDATE_USER_SEX_ERROR("UPDATE_USER_SEX_ERROR", "修改性别失败"),

    UPDATE_USER_AVATAR_SUCCESS("UPDATE_USER_AVATAR_SUCCESS", "修改头像成功"),
    UPDATE_USER_AVATAR_ERROR("UPDATE_USER_AVATAR_ERROR", "修改头像失败"),

    UPDATE_USER_SIGN_SUCCESS("UPDATE_USER_SIGN_SUCCESS", "修改签名成功"),
    UPDATE_USER_SIGN_ERROR("UPDATE_USER_SIGN_ERROR", "修改签名失败"),

    REFRESH_USER_QR_CODE_SUCCESS("REFRESH_USER_QR_CODE_SUCCESS", "刷新二维码成功"),
    REFRESH_USER_QR_CODE_ERROR("REFRESH_USER_QR_CODE_ERROR", "刷新二维码失败"),

    ADD_FRIEND_APPLY_SUCCESS("ADD_FRIEND_APPLY_SUCCESS", "好友申请发送成功"),
    ADD_FRIEND_APPLY_ERROR("ADD_FRIEND_APPLY_ERROR", "好友申请发送失败"),

    ACCEPT_FRIEND_APPLY_SUCCESS("ACCEPT_FRIEND_APPLY_SUCCESS", "接受好友申请成功"),
    ACCEPT_FRIEND_APPLY_ERROR("ACCEPT_FRIEND_APPLY_ERROR", "接受好友申请失败"),

    DELETE_FRIEND_SUCCESS("DELETE_FRIEND_SUCCESS", "删除好友成功"),
    DELETE_FRIEND_ERROR("DELETE_FRIEND_ERROR", "删除好友失败"),

    UPDATE_GROUP_NAME_SUCCESS("UPDATE_GROUP_NAME_SUCCESS", "修改群名成功"),
    UPDATE_GROUP_NAME_ERROR("UPDATE_GROUP_NAME_ERROR", "修改群名失败"),

    ADD_USER_ID_LIST_ILLEGAL("ADD_USER_ID_LIST_ILLEGAL", "添加群组成员ID格式不对"),
    REMOVE_USER_ID_LIST_ILLEGAL("REMOVE_USER_ID_LIST_ILLEGAL", "移除群组成员ID格式不对"),

    ADD_OR_REMOVE_MEMBERS_SUCCESS("ADD_OR_REMOVE_MEMBERS_SUCCESS", "添加或删除群组成员失败"),
    ADD_OR_REMOVE_MEMBERS_ERROR("ADD_OR_REMOVE_MEMBERS_ERROR", "添加或删除群组成员失败"),

    ADD_FRIENDS_CIRCLE_SUCCESS("ADD_FRIENDS_CIRCLE_SUCCESS", "发朋友圈成功"),
    ADD_FRIENDS_CIRCLE_ERROR("ADD_FRIENDS_CIRCLE_ERROR", "发朋友圈失败"),

    LIKE_FRIENDS_CIRCLE_SUCCESS("LIKE_FRIENDS_CIRCLE_SUCCESS", "朋友圈点赞成功"),
    LIKE_FRIENDS_CIRCLE_ERROR("LIKE_FRIENDS_CIRCLE_ERROR", "朋友圈点赞失败"),

    UNLIKE_FRIENDS_CIRCLE_SUCCESS("UNLIKE_FRIENDS_CIRCLE_SUCCESS", "朋友圈取消点赞成功"),
    UNLIKE_FRIENDS_CIRCLE_ERROR("UNLIKE_FRIENDS_CIRCLE_ERROR", "朋友圈取消点赞失败"),

    REFRESH_USER_LASTEST_CIRCLE_PHOTOS_SUCCESS("REFRESH_USER_LASTEST_CIRCLE_PHOTOS_SUCCESS", "更新用户最新N张朋友圈图片成功"),
    REFRESH_USER_LASTEST_CIRCLE_PHOTOS_ERROR("REFRESH_USER_LASTEST_CIRCLE_PHOTOS_ERROR", "更新用户最新N张朋友圈图片失败"),

    UPDATE_USER_REMARKS_SUCCESS("UPDATE_USER_REMARKS_SUCCESS", "更新用户备注信息成功"),
    UPDATE_USER_REMARKS_ERROR("UPDATE_USER_REMARKS_ERROR", "更新用户备注信息失败"),

    UPDATE_USER_STAR_FRIEND_SUCCESS("UPDATE_USER_STAR_FRIEND_SUCCESS", "设置或取消星标朋友成功"),
    UPDATE_USER_STAR_FRIEND_ERROR("UPDATE_USER_STAR_FRIEND_ERROR", "设置或取消星标朋友失败"),

    ADD_USER_ADDRESS_SUCCESS("ADD_USER_ADDRESS_SUCCESS", "保存地址成功"),
    ADD_USER_ADDRESS_ERROR("ADD_USER_ADDRESS_ERROR", "保存地址失败"),

    MODIFY_USER_ADDRESS_SUCCESS("MODIFY_USER_ADDRESS_SUCCESS", "修改地址成功"),
    MODIFY_USER_ADDRESS_ERROR("MODIFY_USER_ADDRESS_ERROR", "修改地址失败"),

    DELETE_USER_ADDRESS_SUCCESS("DELETE_USER_ADDRESS_SUCCESS", "删除地址成功"),
    DELETE_USER_ADDRESS_ERROR("DELETE_USER_ADDRESS_ERROR", "删除地址失败"),

    OSS_CREATE_BUCKET_SUCCESS("OSS_CREATE_BUCKET_SUCCESS", "创建存储空间成功"),
    OSS_CREATE_BUCKET_ERROR("OSS_CREATE_BUCKET_ERROR", "创建存储空间失败"),

    OSS_DELETE_BUCKET_SUCCESS("OSS_DELETE_BUCKET_SUCCESS", "删除存储空间成功"),
    OSS_DELETE_BUCKET_ERROR("OSS_DELETE_BUCKET_ERROR", "删除存储空间失败"),

    INIT_AREA_SUCCESS("INIT_AREA_SUCCESS", "初始化省市区成功"),
    INIT_AREA_ERROR("INIT_AREA_ERROR", "初始化省市区失败"),

    UPLOAD_POSITION_INFO_SUCCESS("UPLOAD_POSITION_INFO_SUCCESS", "上传位置信息成功"),
    UPLOAD_POSITION_INFO_ERROR("UPLOAD_POSITION_INFO_ERROR", "上传位置信息失败"),

    DELETE_POSITION_INFO_SUCCESS("DELETE_POSITION_INFO_SUCCESS", "删除位置信息成功"),
    DELETE_POSITION_INFO_ERROR("DELETE_POSITION_INFO_ERROR", "删除位置信息失败"),
    ;

    ResponseMsg(String responseCode, String responseMessage) {
        this.responseCode = responseCode;
        this.responseMessage = responseMessage;
    }

    private String responseCode;
    private String responseMessage;

    public String getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    public String getResponseMessage() {
        return responseMessage;
    }

    public void setResponseMessage(String responseMessage) {
        this.responseMessage = responseMessage;
    }
}
